- name: add DO repository
  apt_repository:
    repo: deb https://repos.insights.digitalocean.com/apt/do-agent/ main main
    state: present

- name: Add DP apt signing key
  apt_key:
    url: https://repos.insights.digitalocean.com/sonar-agent.asc
    state: present

- name: Install do-agent
  apt:
    update_cache: yes
    pkg:
      - do-agent
    state: present
